### PR TITLE
Convert model directives

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For RobotLocomotion/drake#17223.

This is about the first 50% of my changes to the unit test.  I have at least one more PR for the unit test on the way, then probably some rewrites of the implementation as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/marcoag/drake/4)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review and merge, please.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/marcoag/drake/4)* status: 0 of 28 files reviewed, all discussions resolved

**Review by marcoag — APPROVED** [review]
:lgtm:

> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/marcoag/drake/4#-:-NYXid0o-H-ZFDqn1q2a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
Thanks!

For my part, I'd be okay if you wanted to merge this and we can let Eric review it as part https://github.com/RobotLocomotion/drake/pull/17223.

**Comment by marcoag** [comment]
I like that idea, that way I can check if there's something left from his comments in https://github.com/RobotLocomotion/drake/pull/17223 while waiting for his review.

Thanks for all the improvements!

**Pull request merged**
